
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "devops-tools"
  name: new
  labels:
    app: hello-app
    name: hello-app
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - image: alaaelmansy/hello_app:${BUILD_NUMBER}
        name: hello-app
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: devops-tools
  labels:
    app: hello-app
    name: hello-app
  
spec:
  ports:
  - name: hello-app
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30010
  selector:
    app: hello-app
  type: LoadBalancer
status:
  loadBalancer: {}
